module.exports = {
    STAGE: 'PROD',
    PORT: 5000,
    DATABASE_NAME: '',
    DATABASE_USER: '',
    DATABASE_PASSWORD: '',
    DATABASE_HOST: '',
    LOGGING: false,
    DIALECT: 'mysql',
    DB_ALTER: { alter: false },
    JWT_SECRET_KEY: '',
    LEVEL: 0,
    LOCAL_UPLOAD_FOLDER: './uploads',
    SENDGRID_API_KEY: '',
    FROM_EMAIL: '',
    FROM_NAME: 'Bharat',
    SUBDOMAIN_LENGTH: '5',
    FREE_DOMAIN: '',
    CRON_ENABLED: false,
    DOMAIN_VERIFICATION_TOKEN_SIZE: 16,
    SYSTEM_ADMIN_EMAIL: '',
    ZIP_UPLOAD_FOLDER: '/prod-uploads',
    ZIP_EXTRACT_FOLDER: '/prod-websites/',
    STATIC_MAX_AGE: 300,
    OPEN_AI_API_KEY: '',
}